"""empty message

Revision ID: 1419ed81bfbb
Revises: 2a95a9014f4e
Create Date: 2015-04-01 14:26:10.425246

"""

# revision identifiers, used by Alembic.
revision = '1419ed81bfbb'
down_revision = '2a95a9014f4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('community_contribute', sa.String(), nullable=True))
    op.add_column('user', sa.Column('community_need', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'community_need')
    op.drop_column('user', 'community_contribute')
    ### end Alembic commands ###
